services:
  mysql:
    container_name: mysql-bsn
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password         # Root password for MySQL
      MYSQL_USER: username                      # MySQL username
      MYSQL_PASSWORD: password                  # Password for the MySQL user
      MYSQL_DATABASE: book_social_network       # Default database
    volumes:
      - mysql_data:/var/lib/mysql               # Persistent storage for MySQL
    ports:
      - "3306:3306"                             # Expose MySQL on port 3306
    networks:
      - spring-demo
    restart: unless-stopped                     # Restart policy

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"                             # Web interface for MailDev
      - "1025:1025"                             # SMTP server for MailDev
    networks:
      - spring-demo                             # Connect to the same network

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"                             # Map Keycloak port 8080 to 9090 on host
    environment:
      KEYCLOAK_ADMIN: admin                     # Keycloak admin username
      KEYCLOAK_ADMIN_PASSWORD: admin            # Keycloak admin password
    networks:
      - spring-demo
    command:
      - "start-dev"                             # Keycloak development mode

networks:
  spring-demo:
    driver: bridge                              # Network bridge for container communication

volumes:
  mysql_data:
    driver: local                               # Persistent volume for MySQL data
  keycloak_data:
    driver: local                               # Persistent volume for Keycloak data (if needed)
