spring:
  datasource:
    url: jdbc:mysql://localhost:3307/book_social_network  # MySQL default port is 3306
    username: username                                    # MySQL username
    password: password                                    # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver           # MySQL driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate dialect for MySQL
  mail:
    host: localhost
    port: 1025
    username: bharat
    password: bharat
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: VjE2ZkZHc0lLZkdyNTFZcmxjWmZZZDg4RlZyQlJGcFlGSWZGZ0FoMQ==
      expiration: 43545600
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088


